### PR TITLE
Start fixing patches (Unfinished)

### PR DESCRIPTION
**Pull request by TonimatasDEV**
Fix some patches

633 total hunk failures
91 fixed by toni
435 fixed by c0d3
107 still to be fixed

### CODE REVIEW

**Comment by TonimatasDEV** [comment]
@C0D3-M4513R I don't have much time for it at the moment. Merge it if you change more things

**Comment by C0D3-M4513R** [comment]
Sure. I could also just edit this pr tho.

What I do will depend on if other people also wanna help or not.

**Comment by TonimatasDEV** [comment]
> Sure. I could also just edit this pr tho.
> 
> What I do will depend on if other people also wanna help or not.

Okay, I'll keep informed and try to do something in my spare time.

**Comment by C0D3-M4513R** [comment]
If you are going to edit patch files, I suggest you instruct your editor to keep whitespace lines. I did that when editing patch files for 1.20.3 pretty quickly

**Comment by TonimatasDEV** [comment]
> If you are going to edit patch files, I suggest you instruct your editor to keep whitespace lines. I did that when editing patch files for 1.20.3 pretty quickly

How?

**Comment by C0D3-M4513R** [comment]
image

**Comment by C0D3-M4513R** [comment]
Also small hack: `projects/clean/build/applyPatches/output.zip` contains the clean minecraft project with srg names. If you extract those over the clean sources you will have an easier time patching.
image
I also commented out the `dependsOn ':clean:extractMapped'` in the in `setup` task in the `build.gradle`. This makes it so, that the clean sources are not updated when running `setup`.

**Pull request merged**
